export const apprenticeData = [
  {
    name: "jonathan_p",
    techRoles: ["Warrior", "Paladin"],
    nonTechRoles: ["Scribe", "Healer"],
    siteUrl: "https://github.com/jonathanprozzi",
    twitterHandle: "jonathanprozzi",
  },
  {
    name: "earth2travis",
    techRoles: [],
    nonTechRoles: ["Cleric", "Monk"],
    siteUrl: "https://github.com/earth2travis",
    twitterHandle: "earth2travis",
  },
  {
    name: "tenfinney",
    techRoles: ["Archer", "Warrior", "Wizard"],
    nonTechRoles: ["Rogue", "Monk"],
    siteUrl: "https://github.com/tenfinney",
    twitterHandle: "tenfinney",
  },
  {
    name: "DrHongo",
    techRoles: ["Warrior", "Paladin"],
    nonTechRoles: [],
    siteUrl: "https://github.com/DrHongos",
    twitterHandle: "Lucas19710505",
  },
  {
    name: "earth2travis",
    techRoles: [],
    nonTechRoles: ["Cleric", "Monk"],
    siteUrl: "https://github.com/earth2travis",
    twitterHandle: "earth2travis",
  },
  {
    name: "earth2travis",
    techRoles: [],
    nonTechRoles: ["Cleric", "Monk"],
    siteUrl: "https://github.com/earth2travis",
    twitterHandle: "earth2travis",
  },
  {
    name: "earth2travis",
    techRoles: [],
    nonTechRoles: ["Cleric", "Monk"],
    siteUrl: "https://github.com/earth2travis",
    twitterHandle: "earth2travis",
  },
];
